### ISSUE TITLE
Add RPM packaging for systemd and interactive support on Linux.

### ISSUE THREAD

**Issue by niggemannmj** [nccgroup/log4j-jndi-be-gone#4]
This project would be a lot more useful for mitigating the log4j 2.x JndiLookup vulnerability if it offered RPMs that can easily be installed on Linux systems that would impact the system wide installation of java and would hook into systemd to provide a default environment for initiating the java agent. 

Gradle can easily support RPM packaging using the nebula.rpm plugin.

The systemd environment can use the _JAVA_OPTIONS environment variable to define the agent which should work from Java 6 through Java 17 though it's deprecated from Java 9 onward.

The RPM would include configuration files to setup the systemd default environment and the interactive login profile. It would also include a post installation scriptlet to trigger systemd to update to the _JAVA_OPTIONS environment and a post removal scriptlet to remove the _JAVA_OPTIONS environment.

**Comment by ChaosData** [comment]
I think that would be a bit too invasive (and too much magic) and there's no reason why users cannot simply modify their service definitions to add the option directly to the command, or, as you suggest, the aforementioned environment variable.

Separately, is there any simpler way to simply generate RPM packages than a 3rd party plugin in the gradle config?
I don't really think that such packaging belongs there, or really, in this codebase at all.

Also, from what I can see in your pr, this just bundles the jar, systemd config, post install and post remove scripts, and a separate script that gets injected into the default profile by most shells; the last of which is super invasive and dangerous, especially if someone were already using that env var (or the alternative mentioned in the pr thread).
